export const AppConstant = {

  TEST_USER_NAME: 'testUser',
  ENV_QA: 'test',
  ENV_PROD: 'production',
  ENV_STAGING: 'staging',
  ENV_DEVSERVER: 'devServer',
  ENV_LOCAL: 'localhost',
  ENV_DEVELOPMENT: 'development',
  DOCUMENT_DOWNLOAD_TYPE: 'Download',
  AUTHORIZATION_TYPE: 'Bearer ',
  DATE_FORMAT: 'MMM dd, yyyy',
  DATETIME_FORMAT: 'medium',

  ENV_CHECK: 'ENV',
  SMSESSION: 'SMSESSION',

  HTTP_STATUS_CODE_NOT_AUTHORIZE: 401,
  HTTP_STATUS_CODE_FORBIDDEN: 403,
  HTTP_STATUS_CODE_NOT_AVAILABLE: 0,

  // timeout 1 hours //timeout after 8 hours of idle
  TIMEOUT_TIME: 60 * 60 * 5,
  // idle check 10 mins // idle check after 15 mints
  TIMEOUT_IDLE_TIME: 60 * 15,
  // trigger every 5 mins // trigger every 10 mins
  KEEPALIVE_INTERVAL: 60 * 10,

  // DATETIME_FORMAT: 'MMM d, y h:mm:ss a z',
  CURRENCY_CODE_US: 'USD',
  LANG_US: 'en',
  LANG_JAPANESE: 'ja',
  LANG_FRENCH: 'fr',

  NotAuthorizedUrl: '/notAuthorized',
  SessionExpiredUrl: '/sessionExpired',
  MaintenanceUrl: '/downMaintenance',

  // login
  loginUrl: 'api/login',
  COOKIE_USER_NAME: 'USERNAME',
  COOKIE_GROUP_LIST: 'GROUPLIST',
  COOKIE_PERSON_NAME: 'PERSON_NAME',
  COOKIE_PERSON_ID: 'PERSONID',
  loginMessage: 'Logging in, please wait...',

  // api
  keepAliveConnection: 'api/keepAliveConnection',

  siteContactRequiredMessage: 'Site Contact Name is Required',
  siteContactMinMessage: 'Site Contact Name should be at least more than one character',
  orderFromRequiredMessage: 'Order From field is Required',
  orderFromMinMessage: 'Order From Name should be at least more than one character',
  startDateRequiredMessage: 'Start Date is Required',
  completionDateRequiredMessage: 'Completion Date is Required',
  fixedBidRequiredMessage: 'Fixed Bid Amount is Required',
  resourceTitleRequiredMessage: 'resource Title Date is Required',
  estHoursRequiredMessage: 'Est. Hours is Required',
  rateRequiredMessage: 'Rate is Required',
  projectTitleRequiredMessage: 'Project Title is Required',
  projectTitleMinMessage: 'Project Title should be at least more than one character',
  descAllServeRequiredMessage: 'Description is Required',
  descAllServeMinMessage: 'Description should be at least more than two character',
  accountNoRequiredMessage: 'Account No. is Required',
  costCenterRequiredMessage: 'Cost center is Required',
  distributionRequiredMessage: 'Please fill the Distribution %',
  percentMessage: 'Distribution percent(%) is either equal or exceeding 100%',
  approvalRequiredMessage: 'At least one Approval Name must be entered',
  approvalLimitMessage: "Your Approval Amount exceeds the authorization limit of added approver's",
  numberOfRowsToAddValidate: 'Maximum of 100 Rows is allowed to add at one instance',
  tableRequiredMsg: 'Please fill the unfilled fields on this table',
  CoordinatorSiteContactNameMatch: 'Project Coodinator Name and Site Contact Name cannot be same',
  siteContactCoordinatorNameMatch: 'Site Contact Name and Project Coodinator Name cannot be same',
  siteContactApproverNameMatch: 'Site Contact Name and Approver Name cannot be same',
  projectCoodinatorApproverNameMatch: 'Project Coodinator Name and Approver Name cannot be same',
  selfCoordinatorNameMatch: 'Cannot tag yourself as Project Coordinator Name',
  selfApproverNameMatch: 'Cannot tag yourself as an Approver',
  sameApproverNameTwice: 'Cannot enter same Approver twice',
  submitCheckOfDistribution: 'Distribution percentage should be equal to 100%',
  submitCheckOfDistributionForZero: 'Distribution percentage cannot have zero values in it',
  saveAsDraftValidationForAccounting: 'At least Account No. and Cost Center fields must be inserted before saving as draft',
  approvalAmountZero: 'Approval Amount cannot not be zero',
  creatorAsApproverByAdmin: 'cannot be an approvar',
  CorpPSERFEDashboardDescription: 'This RFE is for Professional Services for those locations deployed into',
  PSERFEDashboardDescriptionStart: 'This RFE is for Professional Services for those',
  PSERFEDashboardDescriptionMiddle: 'deployed in SAP and that are still in',
  PSERFEDashboardDescriptionLast: '(ex: HIS / M*Modal)',
  CorpHSITERFEDashboardDescription: 'This RFE is for the purchase of Hardware/Software and associated Maintenance/Software Support, Memberships and Miscellaneous purchases for locations deployed into',
  HSITERFEDashboardDescription: 'This RFE is for the purchase of Hardware/Software and associated Maintenance/Software Support, Memberships and Miscellaneous purchases for locations still in PeopleSoft (HIS/M*Modal)',

  inValidAccountNumber: 'Please enter valid Account Number\'s',
  inValidCostCenter: 'Please enter valid Cost Center\'s',
  inValidAccountNumberAndCostCenter: 'Please enter valid Account Number\'s and Cost Center\'s.',
  nameNotAvailableMsg: 'This name is not available',
  supplierNameNotAvailableMsg: 'This Supplier Name does not exist',
  costCenterValueInvalidMsg: 'This cost center value is invalid',
  wrongNameFormat: 'Wrong name format',
  closePopups: 'Please select values from the pop-up and close them before submitting',

  // Specific error Msgs for container
  siteContactInvalidForContainer: 'Site Contact Name is invalid',
  supplierNameInvalidForContainer: 'Supplier Name is invalid',
  startDateInvalidForContainer: 'Start Date is invalid',
  completionDateInvalidForContainer: 'Completion Date is invalid',
  workerInformationInvalidForContainer: 'Worker Information is invalid',
  fixedBidInvalidForContainer: 'Fixed Bid Amount is invalid',
  projectTitleInvalidForContainer: 'Project Title is invalid',
  descriptionOfServicesInvalidForContainer: 'Description of all Services is invalid',
  accountingInformationInvalidForContainer: 'Accounting Information is invalid',
  approverNameInvalidForContainer: 'Approver Name is invalid',
  inValidAccountNumberForContainer: 'Account Number is invalid',
  inValidCostCenterForContainer: 'Cost Center is invalid',
  approverNameCreatorInvalidForContainer: "RFE Creator and Approval Name cannot be the same",
  projectCoordinatorInvalidForContainer: "Specified Project Coordinator does not exist. Please select a valid name but its a non-mandatory field",
  informationalCopyInvalidForContainer: "Specified Informational Copy Name does not exist. Please select a valid name but its a non-mandatory field",

  CORPPS: 'Corp PS eRFE',
  PS: 'HIS PS eRFE',
  HS: 'HIS HW/SW eRFE',
  CORPHS: 'Corp HW/SW eRFE',
  HOME: 'Home',
  SEARCH: 'Search',
  NEW_RFE: 'New RFE Document',
  VIEW: 'View Documents',
  ADMIN: 'Administration',
  userRole: 'userRole',
  userId: 'userId',
  reload: false,

  printComponentLoad: false,
  newErfeForm: false,
};
